# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: node-fetch
        update-types: ["version-update:semver-major"]
      - dependency-name: antd
        update-types: ["version-update:semver-major"]
      - dependency-name: "@ant-design/icons"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@ant-design/icons-svg"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@storybook/**"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Europe/Rome
    groups:
      minor-actions-dependencies:
        update-types:
        - minor
        - patch
    commit-message:
      include: scope
      prefix: ci
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: monthly
      timezone: Europe/Rome
    commit-message:
      include: scope
      prefix: build
