version: '3'

services:
  reverse-proxy:
    networks:
      - ring
    ports:
      - 80:8080
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
        - host.docker.internal:host-gateway
  back-kit:
    image: microlc/bk-web-components:${BACK_KIT_VERSION:-unstable}
    networks:
        - ring
  element-composer:
    image: microlc/micro-lc-element-composer:${MICRO_LC_ELEMENT_COMPOSER_VERSION:-0.6.0}
    networks:
        - ring

networks:
    ring:
