name: Main

env:
  context: './'
  cache-name: cache-release
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 18.x

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - './package.json'
      - 'packages/**'
      - 'tests/**'
      - '.docker/**'

jobs:
  dispatch-updated-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify CHANGELOG Updates
        uses: tj-actions/changed-files@v41
        id: changelog-updates
        with:
          since_last_remote_commit: 'true'
          files: packages/orchestrator/*.md

      - name: Trigger 'micro-lc.github.io' Updates
        if: steps.changelog-updates.outputs.any_changed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_DOCS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'micro-lc.github.io',
              workflow_id: 'main.yml',
              ref: 'main'
            })

  prepare:
    uses: micro-lc/micro-lc/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/checks.yml@main


  unit-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/unit-tests.yml@main

  e2e-tests:
    uses: micro-lc/micro-lc/.github/workflows/e2e-tests.yml@main

  release-docker:
    needs:
      - checks
      - unit-tests
      - e2e-tests
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    uses: micro-lc/micro-lc/.github/workflows/release-docker.yml@main
    with:
      version: latest
      push: true
    secrets:
      docker_username: ${{ secrets.BOT_DOCKER_USERNAME }}
      docker_token: ${{ secrets.BOT_DOCKER_TOKEN }}
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}
      security_checks_token: ${{ secrets.SECURITY_CHECKS_TOKEN }}
