name: Install

on:
  workflow_call:
    inputs:
      node-version:
        default: 16.x
        required: false
        type: string
      context:
        default: ./
        required: false
        type: string

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
            ./.yarn/install-state.gz
            ./.pnp.cjs
            ./.pnp.loader.mjs
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build Cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            ./node_modules
            ./packages/**/dist
            ./packages/**/node_modules
          key: ${{ runner.os }}-${{ steps.extract_branch.outputs.branch }}-build-${{ github.sha }}

      - name: Playwright Cache
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            /home/runner/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - name: Build
        run: yarn initialize --cleanup

      - name: Prepare Test
        run: yarn prepare-test
