name: Pull on Main

env:
  context: './'
  cache-name: cache-release
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 20.x

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: micro-lc/micro-lc/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/checks.yml@main

  unit-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/unit-tests.yml@main

  e2e-tests:
    uses: micro-lc/micro-lc/.github/workflows/e2e-tests.yml@main

  file-changes:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.filter.outputs.diff }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            diff:
              - '.docker/**'
              - '.github/**'

  test-docker:
    needs:
      - prepare
      - file-changes
    if: needs.file-changes.outputs.diff == 'true'
    uses: micro-lc/micro-lc/.github/workflows/release-docker.yml@main
    with:
      version: latest
      push: false
    secrets:
      docker_username: ${{ secrets.BOT_DOCKER_USERNAME }}
      docker_token: ${{ secrets.BOT_DOCKER_TOKEN }}
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}
      security_checks_token: ${{ secrets.SECURITY_CHECKS_TOKEN }}
