name: Tag CI

env:
  context: './'
  cache-name: cache-release
  node-version: 16.x
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    tags:
      - '@micro-lc/**'
      - 'v2**'

jobs:
  next-version:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
      - name: Compute tag version
        id: get-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$(echo ${VERSION} | sed s/^v//)" >> $GITHUB_OUTPUT

  release-docker:
    needs:
      - next-version

    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: micro-lc/micro-lc/.github/workflows/release-docker.yml@main
    with:
      push: true
      version: ${{ needs.next-version.outputs.version }}
    secrets:
      username: ${{ secrets.BOT_DOCKER_USERNAME }}
      token: ${{ secrets.BOT_DOCKER_TOKEN }}
      security_checks_token: ${{ secrets.SECURITY_CHECKS_TOKEN }}

  release-npm-package:
    name: Release package on npm
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/@micro-lc/') }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Prepare NPM
        id: prepare-npm-package
        run: |
          TAGS=${{ steps.extract_tag.outputs.tag }}
          echo "package=$(echo $TAGS | sed 's/^\(@micro-lc\/\)//' | sed 's/@.*$//')" >> $GITHUB_OUTPUT

      - name: Build
        run: yarn initialize --cleanup ${{ steps.prepare-npm-package.outputs.package }}

      - name: Publish
        working-directory: ./packages/${{ steps.prepare-npm-package.outputs.package }}
        run: yarn npm publish
  
  release-cdn-package:
    name: Release package on cdn.mia-platform.eu
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/@micro-lc/') }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Prepare NPM
        id: prepare-npm-package
        run: |
          TAGS=${{ steps.extract_tag.outputs.tag }}
          echo "package=$(echo $TAGS | sed 's/^\(@micro-lc\/\)//' | sed 's/@.*$//')" >> $GITHUB_OUTPUT

      - name: Build
        run: yarn initialize --cleanup ${{ steps.prepare-npm-package.outputs.package }}

      - name: Publish to Mia CDN
        working-directory: ./packages/${{ steps.prepare-npm-package.outputs.package }}
        run: |
          npm i -g @mia-platform/cdn-publish@0.4.0
          cdn publish -k ${{ secrets.CDN_STORAGE_ACCESS_KEY }} -s "mia-platform" -b 20
